# Generated by Django 5.0.4 on 2024-04-26 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HP', 'hp'), ('LE', 'lenovo'), ('AP', 'apple'), ('SN', 'sony'), ('SM', 'samsung'), ('NK', 'nokia'), ('FR', 'fire'), ('AL', 'ali'), ('As', 'asus')], max_length=2),
        ),
    ]
