# Generated by Django 5.0.4 on 2024-04-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('HP', 'hp'), ('LE', 'lenovo'), ('AP', 'apple'), ('SN', 'sony'), ('SM', 'samsung'), ('NK', 'nokia'), ('FR', 'Dell'), ('AL', 'MSI'), ('AS', 'asus')], max_length=2),
        ),
    ]
