# Generated by Django 5.0.4 on 2024-04-27 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.ImageField(upload_to='')),
                ('state', models.CharField(choices=[('CAI', 'Cairo'), ('ALX', 'Alexandria'), ('ASW', 'Aswan'), ('LXR', 'Luxor'), ('SHR', 'Sharm El Sheikh'), ('HUR', 'Hurghada'), ('DAH', 'Dahab'), ('SFD', 'Safaga'), ('ISL', 'Ismailia'), ('SUE', 'Suez'), ('PNR', 'Port Said'), ('ALM', 'Al Minya'), ('MNF', 'Mansoura'), ('BNH', 'Beni Suef'), ('MTR', 'Marsa Matruh'), ('ASY', 'Asyut'), ('QIN', 'Qena'), ('SWI', 'Swaike'), ('ALM', 'Alamein'), ('TNT', 'Tanta'), ('BLQ', 'Bilbeis'), ('FAY', 'Faiyum'), ('TUR', 'Tura'), ('BAR', 'Baris'), ('RSH', 'Rashid'), ('MIT', 'Mit Ghamr'), ('KHG', 'Kharga'), ('AQF', 'Abu Qurqas')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
