# Generated by Django 5.0.4 on 2024-04-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
