# Generated by Django 5.0.4 on 2024-05-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_status',
            new_name='payment_status',
        ),
    ]
