# Generated by Django 5.0.4 on 2024-05-04 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderplaced',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='orderplaced',
            name='payment',
        ),
    ]
